/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Match, Player } from './types';

export const INITIAL_MATCHES: Match[] = [
  {
    id: 'm1',
    teamA: 'México',
    flagA: '🇲🇽',
    teamB: 'África do Sul',
    flagB: '🇿🇦',
    date: '11/06/2026',
    time: '16:00',
    startsAt: '2026-06-11T19:00:00.000Z',
    status: 'scheduled',
    group: 'Grupo A',
    venue: 'Estadio Azteca',
    city: 'Mexico City',
  },
  {
    id: 'm2',
    teamA: 'Coreia do Sul',
    flagA: '🇰🇷',
    teamB: 'Tchéquia',
    flagB: '🇨🇿',
    date: '11/06/2026',
    time: '23:00',
    startsAt: '2026-06-12T02:00:00.000Z',
    status: 'scheduled',
    group: 'Grupo A',
    venue: 'Estadio Akron',
    city: 'Zapopan',
  },
  {
    id: 'm3',
    teamA: 'Canadá',
    flagA: '🇨🇦',
    teamB: 'Bósnia e Herzegovina',
    flagB: '🇧🇦',
    date: '12/06/2026',
    time: '16:00',
    startsAt: '2026-06-12T19:00:00.000Z',
    status: 'scheduled',
    group: 'Grupo B',
    venue: 'Toronto Stadium',
    city: 'Toronto',
  },
  {
    id: 'm4',
    teamA: 'Estados Unidos',
    flagA: '🇺🇸',
    teamB: 'Paraguai',
    flagB: '🇵🇾',
    date: '12/06/2026',
    time: '22:00',
    startsAt: '2026-06-13T01:00:00.000Z',
    status: 'scheduled',
    group: 'Grupo D',
    venue: 'Los Angeles Stadium',
    city: 'Inglewood',
  },
  {
    id: 'm5',
    teamA: 'Haiti',
    flagA: '🇭🇹',
    teamB: 'Escócia',
    flagB: '🏴',
    date: '13/06/2026',
    time: '22:00',
    startsAt: '2026-06-14T01:00:00.000Z',
    status: 'scheduled',
    group: 'Grupo C',
    venue: 'Boston Stadium',
    city: 'Foxborough',
  },
  {
    id: 'm6',
    teamA: 'Austrália',
    flagA: '🇦🇺',
    teamB: 'Turquia',
    flagB: '🇹🇷',
    date: '14/06/2026',
    time: '01:00',
    startsAt: '2026-06-14T04:00:00.000Z',
    status: 'scheduled',
    group: 'Grupo D',
    venue: 'BC Place',
    city: 'Vancouver',
  },
  {
    id: 'm7',
    teamA: 'Brasil',
    flagA: '🇧🇷',
    teamB: 'Marrocos',
    flagB: '🇲🇦',
    date: '13/06/2026',
    time: '19:00',
    startsAt: '2026-06-13T22:00:00.000Z',
    status: 'scheduled',
    group: 'Grupo C',
    venue: 'New York New Jersey Stadium',
    city: 'East Rutherford',
  },
  {
    id: 'm8',
    teamA: 'Catar',
    flagA: '🇶🇦',
    teamB: 'Suíça',
    flagB: '🇨🇭',
    date: '13/06/2026',
    time: '16:00',
    startsAt: '2026-06-13T19:00:00.000Z',
    status: 'scheduled',
    group: 'Grupo B',
    venue: 'San Francisco Bay Area Stadium',
    city: 'Santa Clara',
  },
];

// O deploy não deve nascer com participantes fictícios. Usuários reais são
// criados pelo login Google, e o admin ainda pode cadastrar alguém manualmente.
export const SEED_PLAYERS: Omit<
  Player,
  'points' | 'exactHits' | 'partialHits' | 'errorHits'
>[] = [];
